# version: '3.8'

services:
  # sql_server:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   container_name: sql_server
  #   restart: always
  #   ports:
  #     - '1433:1433'
  #   environment:
  #     SA_PASSWORD: 'mast8118'
  #     ACCEPT_EULA: 'Y'
  #   networks:
  #     - kda_network
  #   volumes:
  #     - /var/opt/mssql/data:/var/opt/mssql/data
  #     - /var/opt/mssql/log:/var/opt/mssql/log
  #     - /var/opt/mssql/secrets:/var/opt/mssql/secrets

  kca_api:
    container_name: kca_api
    restart: always
    image: mastika/kca_api:1.3.1
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DOCKER_USER=$DOCKER_USER
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: 5
    ports:
      - 7000:7000
    networks:
      - kda_network
    volumes:
      - type: bind
        source: /home/$USER/Documents/logs
        target: /app/logs
      - type: bind
        source: ${HOME}/Documents/kca-assets
        target: /app/dist/public/assets
      # - type: volume
      #   source: assets_files
      #   target: /app/public/assets
    # volumes:
    #   - type: volume
    #     source: assets_files
    #     target: /app/public/assets/files
    #   - type: bind
    #     source: /home/$USER/Documents/kda_assets
    #     target: /app/public/assets/files
    # depends_on:
    # kda_mysql:
    # condition: service_healthy
    stdin_open: true
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "3.00"
    #       memory: 4g

# volumes:
#   assets_files:
# driver: local

networks:
  kda_network:
    external: true
    name: kda_network
