### create
POST http://192.168.10.2:7000/api/contacts/
Content-Type: application/json

{
	"memberId": "123456",
	"NIP": "34244545634534",
	"memberTypeId": 1,
	"unitId": 1,
	"subUnitId": 1,
	"firstName": "mastenk",
	"lastName": "ketut",
	"email" : "mastenk@gmail.com",
	"phone": "08773888"
}

### get
GET  http://192.168.10.2:7000/api/contacts/1
Content-Type: application/json

### update
PUT http://localhost:7000/api/contacts/1
Content-Type: application/json

{
	"firstName": "mastika updated",
	"lastName": "ketut",
	"email" : "mastika@gmail.com",
	"phone": "811899"
}

### delete
DELETE  http://localhost:7000/api/contacts/134234
Content-Type: application/json

### search
GET  http://localhost:7000/api/contacts?page=1
Content-Type: application/json